spring:
  profiles:
    default: local
    group:
      local:
        - console-logging
      prod:
        - console-logging
        - file-error-logging
        - file-warn-logging
    active: prod
log:
  directory: /logs/spring
