package com.dnd.spaced.global.exception;

public enum ExceptionCode {
    VALIDATION_ERROR,
    INVALID_EMAIL,
    INVALID_NICKNAME,
    INVALID_PROFILE_IMAGE,
    INVALID_ROLE,
    INVALID_TOKEN,
    FORBIDDEN_ACCOUNT,
    INVALID_JOB_GROUP,
    EXPIRED_TOKEN,
    UNAUTHORIZED,
    REFRESH_TOKEN_NOT_FOUND,
    INVALID_CATEGORY,
    INVALID_EXAMPLE,
    INVALID_MEANING,
    INVALID_NAME,
    INVALID_PRONUNCIATION,
    UNSUPPORTED_COMMENT_SORT_CONDITION,
    WORD_NOT_FOUND,
    FORBIDDEN_BOOKMARK,
    INVALID_CONTENT
}
