name: CI for Pull Request Test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create application-prod.yml file
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application-prod.yml
          echo "${{ secrets.APPLICATION-PROD }}" > ./src/main/resources/application-prod.yml
          cat ./src/main/resources/application-prod.yml

      # Gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test
